// <auto-generated />
using EventReceiver.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EventReceiver.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("EventReceiver.Domain.Entities.SensorEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnName("Status")
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnName("Timestamp")
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<string>("Valor")
                        .HasColumnName("Valor")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("SensorEvent");
                });

            modelBuilder.Entity("EventReceiver.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnName("Country")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnName("Region")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<int>("SensorEventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SensorName")
                        .IsRequired()
                        .HasColumnName("SensorName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("SensorEventId")
                        .IsUnique();

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("EventReceiver.Domain.Entities.Tag", b =>
                {
                    b.HasOne("EventReceiver.Domain.Entities.SensorEvent", "SensorEvent")
                        .WithOne("Tag")
                        .HasForeignKey("EventReceiver.Domain.Entities.Tag", "SensorEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
